title: "Kobe Zhang | Readme"
author: "Kobe_zyx"
email: "kobezyuxuan@gmail.com"
description: "IT Enthusiast & Student"
baseurl: ""
url: ""

# Markdown 解析设置 
markdown: kramdown
kramdown:
  input: GFM          # 开启 GitHub 风格 Markdown（支持表格、任务列表、删除线等）
  hard_wrap: false    # 像 Obsidian 一样，单次回车不换行，双次回车才换段落
  math_engine: mathjax # 开启 LaTeX 数学公式支持
  syntax_highlighter: rouge # 代码高亮引擎

plugins:
  - jekyll-seo-tag
  - jekyll-feed          # <--- 加上这个
  - jekyll-admin